enableGitInfo = true

title = 'Balestrand Fjord Angling'
theme = 'balevikit-tailwindcss-hugo-theme'
timeout = 90

[imaging]
  anchor = 'Smart'
  hint = 'photo'
  quality = 90
  resampleFilter = 'MitchellNetravali'

[Params]
  ogimage = ""
  keywords = ['Balestrand fjord angling', 'Balestrand', 'Norway', 'Fishing', 'Sightseeing', 'Guide', 'Angling']
  email = "contact@balestrandfjordangling.com"
  address = "Holmen 3, 6899 Balestrand, Norway"
  contrast = 5

[taxonomies]
  tag = 'tags'

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'