enableGitInfo = true

title = 'Balestrand Fjord Angling'
theme = 'balevikit-tailwindcss-hugo-theme'
timeout = 90
baseURL = 'https://balestrandfjordangling.com'

[imaging]
  anchor = 'Smart'
  hint = 'photo'
  quality = 90
  resampleFilter = 'MitchellNetravali'

[Params]
  ogimage = ""
  keywords = ['Balestrand fjord angling', 'Balestrand', 'Norway', 'Fishing', 'Sightseeing', 'Guide', 'Angling']
  email = "contact@balestrandfjordangling.com"
  phone = "+47 900 81 939"
  address = "Holmen 3, 6899 Balestrand, Norway"
  contrast = 2

[taxonomies]
  tag = 'tags'

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

[outputFormats.TXT]
  mediaType = "text/plain"
  isPlainText = true

[outputs]
  home = ["HTML", "JSON", "TXT"]