[build]
  publish = "public"
  command = "git config core.quotepath false && git config core.precomposeunicode true && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.150.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_VERSION = "0.150.0"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.150.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.150.0"
